package org.openhab.binding.hyundaibluelink.internal;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.IOException;
import java.io.InputStream;
import java.net.URL;
import java.util.Enumeration;
import java.util.Optional;
import java.util.jar.Manifest;

import org.junit.jupiter.api.Test;
import org.eclipse.jdt.annotation.NonNullByDefault;

/**
 * Verifies that the build produced an OSGi manifest so the bundle can be
 * installed in openHAB.
 */
@NonNullByDefault
@SuppressWarnings("null")
public class ManifestValidationTest {

        @Test
        public void manifestContainsOsgiHeaders() throws IOException {
                Enumeration<URL> manifests = getClass().getClassLoader().getResources("META-INF/MANIFEST.MF");

                Optional<Manifest> bundleManifest = findBundleManifest(manifests);

                assertTrue(bundleManifest.isPresent(),
                                "META-INF/MANIFEST.MF generated by bnd is missing – the bundle cannot be installed in openHAB.");

                Manifest manifest = bundleManifest.get();
                String bundleSymbolicName = manifest.getMainAttributes().getValue("Bundle-SymbolicName");
                String bundleManifestVersion = manifest.getMainAttributes().getValue("Bundle-ManifestVersion");

                assertTrue("org.openhab.binding.hyundaibluelink".equals(bundleSymbolicName),
                                () -> "Unexpected Bundle-SymbolicName in generated manifest: " + bundleSymbolicName);
                assertTrue("2".equals(bundleManifestVersion),
                                () -> "Generated manifest must declare Bundle-ManifestVersion 2 but was "
                                                + bundleManifestVersion);
        }

        @Test
        public void manifestAllowsFlexibleOrgJsonImport() throws IOException {
                Enumeration<URL> manifests = getClass().getClassLoader().getResources("META-INF/MANIFEST.MF");

                Optional<Manifest> bundleManifest = findBundleManifest(manifests);

                assertTrue(bundleManifest.isPresent(),
                                "META-INF/MANIFEST.MF generated by bnd is missing – the bundle cannot be installed in openHAB.");

                Manifest manifest = bundleManifest.get();
                String importPackage = manifest.getMainAttributes().getValue("Import-Package");

                assertNotNull(importPackage, "Generated manifest is missing the Import-Package header");

                String normalizedImportPackage = importPackage.replace("\r", "").replace("\n", "");

                assertTrue(normalizedImportPackage.contains("org.json;"),
                                () -> "org.json import clause is missing from generated manifest: "
                                                + normalizedImportPackage);
                assertTrue(normalizedImportPackage.contains("org.json;resolution:=optional"),
                                () -> "org.json import must be optional but was " + normalizedImportPackage);
                assertFalse(normalizedImportPackage.contains("org.json;resolution:=optional;version"),
                                () -> "org.json import must not restrict versions but was " + normalizedImportPackage);

                assertFalse(normalizedImportPackage.contains("org.openhab.binding.hyundaibluelink"),
                                () -> "Bundle must not import its own packages but manifest contained: "
                                                + normalizedImportPackage);
        }

        private Optional<Manifest> findBundleManifest(Enumeration<URL> manifests) throws IOException {
                while (manifests.hasMoreElements()) {
                        URL manifestUrl = manifests.nextElement();
                        try (InputStream manifestStream = manifestUrl.openStream()) {
                                Manifest manifest = new Manifest(manifestStream);
                                if ("org.openhab.binding.hyundaibluelink"
                                                .equals(manifest.getMainAttributes().getValue("Bundle-SymbolicName"))) {
                                        return Optional.of(manifest);
                                }
                        }
                }
                return Optional.empty();
        }
}
